apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: data-script
  name: data-script
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data-script
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/app-myapp: "true"
        io.kompose.service: data-script
    spec:
      containers:
        - image: notyouraverageusername/data-script:v1
          name: data-script
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
      restartPolicy: Always
