apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: data
  name: data
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/app-myapp: "true"
        io.kompose.service: data
    spec:
      containers:
        - env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: mydatabase
            - name: MYSQL_PASSWORD
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: root
          image: notyouraverageusername/data:v1
          name: db
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
      restartPolicy: Always
