version: "3"
services:

  front:
    container_name: front
    #build: front/
    image: # image from your github/ instructions in ReadMe
    ports:
      - "3001:3001"
    networks:
      - myapp

  back:
    container_name: api
    # build: back/
    image: # image from your github/ instructions in ReadMe
    ports:
      - "3000:3000"
    networks:
      - myapp

  data:
    container_name: db
    #build: data/
    image: # image from your github/ instructions in ReadMe
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "mydatabase"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - myapp

  data-script:
    container_name: data-script
    ports:
      - "80:80"
    #build: data-script
    image: # image from your github/ instructions in ReadMe
    networks:
      - myapp

networks:
  myapp:
